# Generated by Django 3.0.7 on 2021-08-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_course_name', models.CharField(max_length=50)),
                ('dept_course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_content', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=50)),
                ('media_content', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_name', models.CharField(max_length=50)),
                ('message_content', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notify_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notify_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=50)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('confirmation_code', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocumentManagement.User')),
            ],
        ),
    ]
