# Generated by Django 3.2.5 on 2021-09-09 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMessage',
            fields=[
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('reply_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reply_unread', models.BooleanField(default=True)),
                ('reply_description', models.TextField(max_length=256)),
                ('reply_file', models.FileField(blank=True, upload_to='')),
                ('reply_receiver', models.ManyToManyField(related_name='reply_receiver', to=settings.AUTH_USER_MODEL)),
                ('reply_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_sender', to=settings.AUTH_USER_MODEL)),
                ('replyed_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyed_message', to='DocumentManagement.message')),
            ],
        ),
    ]
