# Generated by Django 3.2.5 on 2021-08-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_confirm_password',
            new_name='user_username',
        ),
    ]
