# Generated by Django 3.2.5 on 2021-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='message_file',
            field=models.FileField(blank=True, upload_to='brother/'),
        ),
    ]
