# Generated by Django 3.2.5 on 2021-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cc_user',
            name='unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
