# Generated by Django 3.2.5 on 2021-09-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0002_replymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_unread',
        ),
        migrations.RemoveField(
            model_name='replymessage',
            name='reply_unread',
        ),
        migrations.AddField(
            model_name='message',
            name='message_cc',
            field=models.ManyToManyField(related_name='message_carbon_copy', to='DocumentManagement.Office'),
        ),
        migrations.AddField(
            model_name='replymessage',
            name='reply_cc',
            field=models.ManyToManyField(related_name='reply_carbon_copy', to='DocumentManagement.Office'),
        ),
    ]
