# Generated by Django 3.0.7 on 2021-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0003_myprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='profile_image',
            field=models.ImageField(default='images/Space3.jpg', upload_to='images/'),
        ),
    ]
