# Generated by Django 3.2.5 on 2021-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0003_alter_sendmessage_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='message_file',
            field=models.FileField(blank=True, upload_to='<bound method Field.value_to_string of <django.db.models.fields.CharField>>/'),
        ),
    ]
