# Generated by Django 3.2.5 on 2021-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0003_auto_20210909_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='replymessage',
            name='reply_unread',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_cc',
        ),
        migrations.AddField(
            model_name='message',
            name='message_cc',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='replymessage',
            name='reply_cc',
        ),
        migrations.AddField(
            model_name='replymessage',
            name='reply_cc',
            field=models.BooleanField(default=False),
        ),
    ]
